export const data: string = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper et nisl at interdum. Duis pellentesque sem malesuada sem vulputate tempus. Sed porta velit ac risus commodo, eget dictum turpis tincidunt. In mi velit, volutpat vitae nibh commodo, tincidunt elementum nibh. Nullam pulvinar vitae leo id gravida. Donec pulvinar elit vel rhoncus accumsan. Integer imperdiet turpis quam, eu hendrerit nulla aliquet id. Donec scelerisque, arcu sit amet ornare suscipit, enim ex varius ligula, sit amet blandit nisl tortor pretium odio. Phasellus dapibus lorem ac sapien eleifend ultrices. Ut sodales sagittis urna. Mauris metus odio, pharetra ac dapibus nec, tempus at risus. Aenean non fermentum nulla.

Curabitur dapibus enim quis porta porta. Integer feugiat nisl a neque finibus commodo non et nisi. Integer euismod turpis neque, nec fringilla ex maximus sit amet. Nam semper erat bibendum, imperdiet tellus id, finibus eros. Praesent ut leo et ligula tempus lacinia egestas ac massa. Pellentesque pellentesque vestibulum eros, non posuere sapien fringilla vitae. Mauris vitae est ultricies, maximus justo et, consectetur ligula. Maecenas a nunc leo. Mauris accumsan neque eu justo consequat efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Duis in pulvinar leo. Integer dignissim risus magna, a tempus ante convallis nec. Proin mauris mi, porta nec volutpat nec, semper ac erat. Suspendisse potenti. Nam egestas pretium felis, at consectetur elit ultricies non. Sed vulputate, tortor vitae tristique aliquet, ante sapien venenatis augue, et bibendum libero magna at turpis. Vestibulum lobortis, ex ut posuere ornare, mi nibh dignissim erat, sit amet fermentum tortor orci ac justo. Phasellus aliquet gravida justo eu condimentum. Vivamus aliquam aliquam risus in suscipit. Phasellus ornare nisl nec nibh gravida, et malesuada erat rutrum. Etiam imperdiet euismod orci sit amet pulvinar.

Donec feugiat ullamcorper massa. In hac habitasse platea dictumst. Phasellus ornare velit tristique neque aliquet, ut accumsan arcu pretium. Cras ut tempor ante. Vestibulum lorem purus, iaculis et cursus sit amet, porttitor sed velit. Sed elementum nec dui rhoncus mattis. Fusce viverra gravida lectus, eget convallis diam ultricies tempor. Suspendisse consectetur elementum libero a mattis.

Quisque feugiat dui sagittis neque condimentum, sed fermentum dui aliquam. Nullam blandit lacinia consequat. Sed non fermentum ex, mollis ultrices ante. Suspendisse potenti. Nunc lorem sapien, pellentesque in nibh id, condimentum hendrerit massa. Ut lacinia justo at vehicula gravida. Morbi quis arcu nec neque facilisis vulputate sollicitudin eget est. Quisque non dapibus diam. Quisque feugiat condimentum dolor quis iaculis. In pharetra ut arcu vel mattis.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper et nisl at interdum. Duis pellentesque sem malesuada sem vulputate tempus. Sed porta velit ac risus commodo, eget dictum turpis tincidunt. In mi velit, volutpat vitae nibh commodo, tincidunt elementum nibh. Nullam pulvinar vitae leo id gravida. Donec pulvinar elit vel rhoncus accumsan. Integer imperdiet turpis quam, eu hendrerit nulla aliquet id. Donec scelerisque, arcu sit amet ornare suscipit, enim ex varius ligula, sit amet blandit nisl tortor pretium odio. Phasellus dapibus lorem ac sapien eleifend ultrices. Ut sodales sagittis urna. Mauris metus odio, pharetra ac dapibus nec, tempus at risus. Aenean non fermentum nulla.

Curabitur dapibus enim quis porta porta. Integer feugiat nisl a neque finibus commodo non et nisi. Integer euismod turpis neque, nec fringilla ex maximus sit amet. Nam semper erat bibendum, imperdiet tellus id, finibus eros. Praesent ut leo et ligula tempus lacinia egestas ac massa. Pellentesque pellentesque vestibulum eros, non posuere sapien fringilla vitae. Mauris vitae est ultricies, maximus justo et, consectetur ligula. Maecenas a nunc leo. Mauris accumsan neque eu justo consequat efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Duis in pulvinar leo. Integer dignissim risus magna, a tempus ante convallis nec. Proin mauris mi, porta nec volutpat nec, semper ac erat. Suspendisse potenti. Nam egestas pretium felis, at consectetur elit ultricies non. Sed vulputate, tortor vitae tristique aliquet, ante sapien venenatis augue, et bibendum libero magna at turpis. Vestibulum lobortis, ex ut posuere ornare, mi nibh dignissim erat, sit amet fermentum tortor orci ac justo. Phasellus aliquet gravida justo eu condimentum. Vivamus aliquam aliquam risus in suscipit. Phasellus ornare nisl nec nibh gravida, et malesuada erat rutrum. Etiam imperdiet euismod orci sit amet pulvinar.

Donec feugiat ullamcorper massa. In hac habitasse platea dictumst. Phasellus ornare velit tristique neque aliquet, ut accumsan arcu pretium. Cras ut tempor ante. Vestibulum lorem purus, iaculis et cursus sit amet, porttitor sed velit. Sed elementum nec dui rhoncus mattis. Fusce viverra gravida lectus, eget convallis diam ultricies tempor. Suspendisse consectetur elementum libero a mattis.

Quisque feugiat dui sagittis neque condimentum, sed fermentum dui aliquam. Nullam blandit lacinia consequat. Sed non fermentum ex, mollis ultrices ante. Suspendisse potenti. Nunc lorem sapien, pellentesque in nibh id, condimentum hendrerit massa. Ut lacinia justo at vehicula gravida. Morbi quis arcu nec neque facilisis vulputate sollicitudin eget est. Quisque non dapibus diam. Quisque feugiat condimentum dolor quis iaculis. In pharetra ut arcu vel mattis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper et nisl at interdum. Duis pellentesque sem malesuada sem vulputate tempus. Sed porta velit ac risus commodo, eget dictum turpis tincidunt. In mi velit, volutpat vitae nibh commodo, tincidunt elementum nibh. Nullam pulvinar vitae leo id gravida. Donec pulvinar elit vel rhoncus accumsan. Integer imperdiet turpis quam, eu hendrerit nulla aliquet id. Donec scelerisque, arcu sit amet ornare suscipit, enim ex varius ligula, sit amet blandit nisl tortor pretium odio. Phasellus dapibus lorem ac sapien eleifend ultrices. Ut sodales sagittis urna. Mauris metus odio, pharetra ac dapibus nec, tempus at risus. Aenean non fermentum nulla.

Curabitur dapibus enim quis porta porta. Integer feugiat nisl a neque finibus commodo non et nisi. Integer euismod turpis neque, nec fringilla ex maximus sit amet. Nam semper erat bibendum, imperdiet tellus id, finibus eros. Praesent ut leo et ligula tempus lacinia egestas ac massa. Pellentesque pellentesque vestibulum eros, non posuere sapien fringilla vitae. Mauris vitae est ultricies, maximus justo et, consectetur ligula. Maecenas a nunc leo. Mauris accumsan neque eu justo consequat efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Duis in pulvinar leo. Integer dignissim risus magna, a tempus ante convallis nec. Proin mauris mi, porta nec volutpat nec, semper ac erat. Suspendisse potenti. Nam egestas pretium felis, at consectetur elit ultricies non. Sed vulputate, tortor vitae tristique aliquet, ante sapien venenatis augue, et bibendum libero magna at turpis. Vestibulum lobortis, ex ut posuere ornare, mi nibh dignissim erat, sit amet fermentum tortor orci ac justo. Phasellus aliquet gravida justo eu condimentum. Vivamus aliquam aliquam risus in suscipit. Phasellus ornare nisl nec nibh gravida, et malesuada erat rutrum. Etiam imperdiet euismod orci sit amet pulvinar.

Donec feugiat ullamcorper massa. In hac habitasse platea dictumst. Phasellus ornare velit tristique neque aliquet, ut accumsan arcu pretium. Cras ut tempor ante. Vestibulum lorem purus, iaculis et cursus sit amet, porttitor sed velit. Sed elementum nec dui rhoncus mattis. Fusce viverra gravida lectus, eget convallis diam ultricies tempor. Suspendisse consectetur elementum libero a mattis.

Quisque feugiat dui sagittis neque condimentum, sed fermentum dui aliquam. Nullam blandit lacinia consequat. Sed non fermentum ex, mollis ultrices ante. Suspendisse potenti. Nunc lorem sapien, pellentesque in nibh id, condimentum hendrerit massa. Ut lacinia justo at vehicula gravida. Morbi quis arcu nec neque facilisis vulputate sollicitudin eget est. Quisque non dapibus diam. Quisque feugiat condimentum dolor quis iaculis. In pharetra ut arcu vel mattis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper et nisl at interdum. Duis pellentesque sem malesuada sem vulputate tempus. Sed porta velit ac risus commodo, eget dictum turpis tincidunt. In mi velit, volutpat vitae nibh commodo, tincidunt elementum nibh. Nullam pulvinar vitae leo id gravida. Donec pulvinar elit vel rhoncus accumsan. Integer imperdiet turpis quam, eu hendrerit nulla aliquet id. Donec scelerisque, arcu sit amet ornare suscipit, enim ex varius ligula, sit amet blandit nisl tortor pretium odio. Phasellus dapibus lorem ac sapien eleifend ultrices. Ut sodales sagittis urna. Mauris metus odio, pharetra ac dapibus nec, tempus at risus. Aenean non fermentum nulla.

Curabitur dapibus enim quis porta porta. Integer feugiat nisl a neque finibus commodo non et nisi. Integer euismod turpis neque, nec fringilla ex maximus sit amet. Nam semper erat bibendum, imperdiet tellus id, finibus eros. Praesent ut leo et ligula tempus lacinia egestas ac massa. Pellentesque pellentesque vestibulum eros, non posuere sapien fringilla vitae. Mauris vitae est ultricies, maximus justo et, consectetur ligula. Maecenas a nunc leo. Mauris accumsan neque eu justo consequat efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Duis in pulvinar leo. Integer dignissim risus magna, a tempus ante convallis nec. Proin mauris mi, porta nec volutpat nec, semper ac erat. Suspendisse potenti. Nam egestas pretium felis, at consectetur elit ultricies non. Sed vulputate, tortor vitae tristique aliquet, ante sapien venenatis augue, et bibendum libero magna at turpis. Vestibulum lobortis, ex ut posuere ornare, mi nibh dignissim erat, sit amet fermentum tortor orci ac justo. Phasellus aliquet gravida justo eu condimentum. Vivamus aliquam aliquam risus in suscipit. Phasellus ornare nisl nec nibh gravida, et malesuada erat rutrum. Etiam imperdiet euismod orci sit amet pulvinar.

Donec feugiat ullamcorper massa. In hac habitasse platea dictumst. Phasellus ornare velit tristique neque aliquet, ut accumsan arcu pretium. Cras ut tempor ante. Vestibulum lorem purus, iaculis et cursus sit amet, porttitor sed velit. Sed elementum nec dui rhoncus mattis. Fusce viverra gravida lectus, eget convallis diam ultricies tempor. Suspendisse consectetur elementum libero a mattis.

Quisque feugiat dui sagittis neque condimentum, sed fermentum dui aliquam. Nullam blandit lacinia consequat. Sed non fermentum ex, mollis ultrices ante. Suspendisse potenti. Nunc lorem sapien, pellentesque in nibh id, condimentum hendrerit massa. Ut lacinia justo at vehicula gravida. Morbi quis arcu nec neque facilisis vulputate sollicitudin eget est. Quisque non dapibus diam. Quisque feugiat condimentum dolor quis iaculis. In pharetra ut arcu vel mattis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper et nisl at interdum. Duis pellentesque sem malesuada sem vulputate tempus. Sed porta velit ac risus commodo, eget dictum turpis tincidunt. In mi velit, volutpat vitae nibh commodo, tincidunt elementum nibh. Nullam pulvinar vitae leo id gravida. Donec pulvinar elit vel rhoncus accumsan. Integer imperdiet turpis quam, eu hendrerit nulla aliquet id. Donec scelerisque, arcu sit amet ornare suscipit, enim ex varius ligula, sit amet blandit nisl tortor pretium odio. Phasellus dapibus lorem ac sapien eleifend ultrices. Ut sodales sagittis urna. Mauris metus odio, pharetra ac dapibus nec, tempus at risus. Aenean non fermentum nulla.

Curabitur dapibus enim quis porta porta. Integer feugiat nisl a neque finibus commodo non et nisi. Integer euismod turpis neque, nec fringilla ex maximus sit amet. Nam semper erat bibendum, imperdiet tellus id, finibus eros. Praesent ut leo et ligula tempus lacinia egestas ac massa. Pellentesque pellentesque vestibulum eros, non posuere sapien fringilla vitae. Mauris vitae est ultricies, maximus justo et, consectetur ligula. Maecenas a nunc leo. Mauris accumsan neque eu justo consequat efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Duis in pulvinar leo. Integer dignissim risus magna, a tempus ante convallis nec. Proin mauris mi, porta nec volutpat nec, semper ac erat. Suspendisse potenti. Nam egestas pretium felis, at consectetur elit ultricies non. Sed vulputate, tortor vitae tristique aliquet, ante sapien venenatis augue, et bibendum libero magna at turpis. Vestibulum lobortis, ex ut posuere ornare, mi nibh dignissim erat, sit amet fermentum tortor orci ac justo. Phasellus aliquet gravida justo eu condimentum. Vivamus aliquam aliquam risus in suscipit. Phasellus ornare nisl nec nibh gravida, et malesuada erat rutrum. Etiam imperdiet euismod orci sit amet pulvinar.

Donec feugiat ullamcorper massa. In hac habitasse platea dictumst. Phasellus ornare velit tristique neque aliquet, ut accumsan arcu pretium. Cras ut tempor ante. Vestibulum lorem purus, iaculis et cursus sit amet, porttitor sed velit. Sed elementum nec dui rhoncus mattis. Fusce viverra gravida lectus, eget convallis diam ultricies tempor. Suspendisse consectetur elementum libero a mattis.

Quisque feugiat dui sagittis neque condimentum, sed fermentum dui aliquam. Nullam blandit lacinia consequat. Sed non fermentum ex, mollis ultrices ante. Suspendisse potenti. Nunc lorem sapien, pellentesque in nibh id, condimentum hendrerit massa. Ut lacinia justo at vehicula gravida. Morbi quis arcu nec neque facilisis vulputate sollicitudin eget est. Quisque non dapibus diam. Quisque feugiat condimentum dolor quis iaculis. In pharetra ut arcu vel mattis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper et nisl at interdum. Duis pellentesque sem malesuada sem vulputate tempus. Sed porta velit ac risus commodo, eget dictum turpis tincidunt. In mi velit, volutpat vitae nibh commodo, tincidunt elementum nibh. Nullam pulvinar vitae leo id gravida. Donec pulvinar elit vel rhoncus accumsan. Integer imperdiet turpis quam, eu hendrerit nulla aliquet id. Donec scelerisque, arcu sit amet ornare suscipit, enim ex varius ligula, sit amet blandit nisl tortor pretium odio. Phasellus dapibus lorem ac sapien eleifend ultrices. Ut sodales sagittis urna. Mauris metus odio, pharetra ac dapibus nec, tempus at risus. Aenean non fermentum nulla.

Curabitur dapibus enim quis porta porta. Integer feugiat nisl a neque finibus commodo non et nisi. Integer euismod turpis neque, nec fringilla ex maximus sit amet. Nam semper erat bibendum, imperdiet tellus id, finibus eros. Praesent ut leo et ligula tempus lacinia egestas ac massa. Pellentesque pellentesque vestibulum eros, non posuere sapien fringilla vitae. Mauris vitae est ultricies, maximus justo et, consectetur ligula. Maecenas a nunc leo. Mauris accumsan neque eu justo consequat efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Duis in pulvinar leo. Integer dignissim risus magna, a tempus ante convallis nec. Proin mauris mi, porta nec volutpat nec, semper ac erat. Suspendisse potenti. Nam egestas pretium felis, at consectetur elit ultricies non. Sed vulputate, tortor vitae tristique aliquet, ante sapien venenatis augue, et bibendum libero magna at turpis. Vestibulum lobortis, ex ut posuere ornare, mi nibh dignissim erat, sit amet fermentum tortor orci ac justo. Phasellus aliquet gravida justo eu condimentum. Vivamus aliquam aliquam risus in suscipit. Phasellus ornare nisl nec nibh gravida, et malesuada erat rutrum. Etiam imperdiet euismod orci sit amet pulvinar.

Donec feugiat ullamcorper massa. In hac habitasse platea dictumst. Phasellus ornare velit tristique neque aliquet, ut accumsan arcu pretium. Cras ut tempor ante. Vestibulum lorem purus, iaculis et cursus sit amet, porttitor sed velit. Sed elementum nec dui rhoncus mattis. Fusce viverra gravida lectus, eget convallis diam ultricies tempor. Suspendisse consectetur elementum libero a mattis.

Quisque feugiat dui sagittis neque condimentum, sed fermentum dui aliquam. Nullam blandit lacinia consequat. Sed non fermentum ex, mollis ultrices ante. Suspendisse potenti. Nunc lorem sapien, pellentesque in nibh id, condimentum hendrerit massa. Ut lacinia justo at vehicula gravida. Morbi quis arcu nec neque facilisis vulputate sollicitudin eget est. Quisque non dapibus diam. Quisque feugiat condimentum dolor quis iaculis. In pharetra ut arcu vel mattis.`;

interface Route {
	to: string;
	content: any;
}

export const routes: Route[] = [
	{ to: "/page-1", content: "Page 1" },
	{ to: "/page-2", content: "Page 2" },
];

export const scrollToTop = () => {
	window.scrollTo(0, 0);
};
